name: bililive_api_fl
description: Implementation of a selective subset of bililive's APIs.
version: 0.1.0
repository: https://github.com/Kazurin-775/bililive_api_fl

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  # test: ^1.21.0
dependencies:
  brotli: ^0.5.0
  logger: ^1.1.0
  web_socket_channel: ^2.3.0
